apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-writer-binding
  namespace: elastic-stack
subjects:
- kind: ServiceAccount
  name: secret-writer
  namespace: elastic-stack
roleRef:
  kind: Role
  name: secret-writer-role
  apiGroup: rbac.authorization.k8s.io/v1