apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-writer-role
  namespace: elastic-stack
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "list", "watch"]  # Actions that the role allows and that resource into the namespace